### PR TITLE
Fix webapi 61

### LINKED ISSUE #24: Base api call results on the HTTP header, rather than a value in the body of response
Read this: [web-api#61](https://github.com/aau-giraf/web-api/issues/61)

## Background

The web api currently returns HTTP code 200 in its header no matter the result. The body then contains a `"success" : false` when the call failed. Since this is a protocol abuse, the web api should be changed to use proper HTTP error codes, and the client, changed to properly evaluate responses based on the response header.

### PR DESCRIPTION
**Pull request by frederikspang**
relates to aau-giraf/web-api#61
closes #24

this pull request depends on aau-giraf/web-api#118

### CODE REVIEW

File: lib/api/api_exception.dart [hunk 1]
```diff
@@ -24,7 +31,10 @@ class ApiException implements Exception {
   ErrorKey errorKey = ErrorKey.NoError;
 
   /// List of the errors involved in the call
```
Comment (Seraph2) [inline lib/api/api_exception.dart:33]: It is not a list of errors anymore.
